name: Push to Marketplace

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to push (optional - if not provided, will use latest)"
        required: false
        type: string

jobs:
  push_to_marketplace:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get version if not provided
        id: get-version
        if: ${{ !inputs.version }}
        run: |
          # Get version from package.json
          VERSION=$(node -e "console.log(require('./package.json').version);")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set provided version
        id: set-version
        if: ${{ inputs.version }}
        run: |
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT

      # First AWS credential configuration for production
      - name: Configure AWS credentials for production
        id: prod-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GitHubActions-prod-${{ github.run_id }}

      # Get production account ID and pull image
      - name: Pull from Production ECR
        run: |
          PROD_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          echo "PROD_ACCOUNT_ID=${PROD_ACCOUNT_ID}" >> $GITHUB_ENV

          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | \
            docker login --username AWS --password-stdin ${PROD_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

          docker pull ${PROD_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.PROD_IMAGE_NAME }}:${VERSION}

      # Switch to marketplace credentials
      - name: Configure AWS credentials for marketplace
        id: marketplace-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_MARKETPLACE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GitHubActions-marketplace-${{ github.run_id }}

      # Push to marketplace with new credentials
      - name: Push to Marketplace ECR
        run: |
          MARKETPLACE_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)

          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | \
            docker login --username AWS --password-stdin ${MARKETPLACE_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

          docker tag ${PROD_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.PROD_IMAGE_NAME }}:${VERSION} \
            ${MARKETPLACE_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_MARKETPLACE_PRODUCT_NAME }}/${{ secrets.AWS_MARKETPLACE_REPO_NAME }}:${VERSION}

          docker push ${MARKETPLACE_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_MARKETPLACE_PRODUCT_NAME }}/${{ secrets.AWS_MARKETPLACE_REPO_NAME }}:${VERSION}

  notify:
    needs: [push_to_marketplace]
    uses: ./.github/workflows/notify.yml
    with:
      version: ${{ needs.push_to_marketplace.outputs.version }}
      environment: marketplace
    secrets: inherit
