name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout GitHub repository with full history
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for context

      # Step 2: Configure Git identity
      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "kelumalai@presidio.com"

      # Step 3: Setup SSH for GitLab
      - name: Setup SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.presidio.com >> ~/.ssh/known_hosts

      # Step 4: Add GitLab remote
      - name: Add GitLab remote
        run: git remote add gitlab git@gitlab.presidio.com:hai-build/specif-ai-github.git

      # Step 5: Fetch GitLab qa branch
      - name: Fetch GitLab qa branch
        run: git fetch gitlab qa || true  # Ensure GitLab qa branch is fetched

      # Step 6: Checkout GitLab qa branch
      - name: Checkout GitLab qa branch
        run: |
          git checkout qa || git checkout -b qa gitlab/qa

      # Step 7: Merge GitHub main into GitLab qa
      - name: Merge GitHub main into GitLab qa
        run: git merge origin/main --allow-unrelated-histories --strategy-option=theirs || true

      # Step 8: Push only to GitLab qa
      - name: Push Final Changes to GitLab qa branch
        run: git push gitlab qa